apiVersion: v1
kind: Service
metadata:
  name: api-kubernetes-jilf
  labels:
    app: api-kubernetes-jilf
spec:
  type: LoadBalancer
  selector:
    app: apikubernetes
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: None